---
# Rapid Mortality Surveillance (Events)
RMS0: # Rapid Mortality Surveillance events package
  RMS000: RMS0-Rapid_Mortality_Surveillance # Rapid Mortality Surveillance events

# Malaria Aggregate (Aggregate)
MLAG: # Malaria aggregate package
  MLAG00: MLAG-Malaria_Aggregate # Malaria aggregate complete
  MLAGDB: MLAG-Malaria_Aggregate # Malaria aggregate complete dashboard
  MLAGDQ: MLAG-Malaria_Aggregate # Malaria data quality dashboard
  MLAGMP: MLAG-Malaria_Aggregate # Malaria mobile and migrant populations
  MLAGST: MLAG-Malaria_Aggregate # Malaria stock
  MLAGSD: MLAG-Malaria_Aggregate # Malaria stock dashboard

# Malaria Surveillance (Tracker)
MLSO: # Malaria Case Surveillance & Foci Investigation
  MLS0CS: MLS0-Malaria_Case_Surveillance_and_Foci_Investigation # Malaria Case Surveillance
  MLS0FI: MLS0-Malaria_Case_Surveillance_and_Foci_Investigation # Malaria Foci Investigation

# Tuberculosis Aggregate (Aggregate)
TBAG: # Tuberculosis aggregate package
  TBAG00: TBAG-Tuberculosis_Aggregate # TB aggregate complete
  TBAGDB: TBAG-Tuberculosis_Aggregate # TB aggregate complete dashboard
  TBAGHH: TBAG-Tuberculosis_Aggregate # TB aggregate household contacts
  TBAGHD: TBAG-Tuberculosis_Aggregate # TB aggregate household contacts dashboard
  TBAGST: TBAG-Tuberculosis_Aggregate # TB aggregate stock
  TBAGSD: TBAG-Tuberculosis_Aggregate # TB aggregate stock dashboard

# Nutrition Aggregate (Aggregate)
NUTR: 
  NUTR00: NUTR-Nutrition # Nutrition aggregate complete
  NUTRDB: NUTR-Nutrition # Nutrition aggregate complete dashboard
...
